name: ci-helloworld

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: axaypatel0105/helloworldaj:latest
          
      - 
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
         host: 107.21.24.39
         username: ubuntu
         passphrase: ${{ secrets.PASSPHRASE }}
         port: 22
         script: /home/ubuntu/run.sh
